language: java

script:
  - echo "script skipped"

install: 
  - mvn install -DskipTests=false -Dmaven.javadoc.skip=true -B -V

after_success:
  - mv tool/target/tool-1.0-SNAPSHOT-jar-with-dependencies.jar asn1-tool.jar
  - mvn clean test jacoco:report coveralls:report

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: asn1-tool.jar
  skip_cleanup: true
  on:
    tags: true
