language: java

jdk:
  - openjdk8

install: true
 
script:
  - mvn package -DskipTests=false -Dmaven.javadoc.skip=true -B -V

after_success:
  - # Prepare files for deploy stage
  - mv tool/target/tool-1.0-SNAPSHOT-compiler-with-beautifier.jar asn1-compiler-with-google-java-format.jar
  - mv tool/target/tool-1.0-SNAPSHOT-compiler-without-beautifier.jar asn1-compiler.jar
  - mv tool/target/tool-1.0-SNAPSHOT-converter.jar asn1-converter.jar
  - mv runtime/target/runtime-1.0-SNAPSHOT.jar asn1-runtime.jar
  - # Generate coverage report
  - mvn clean jacoco:prepare-agent test jacoco:report coveralls:report
 
 
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: 
  - asn1-compiler-with-google-java-format.jar
  - asn1-compiler.jar
  - asn1-converter.jar
  - asn1-runtime.jar
  skip_cleanup: true
  provider: script
  script:
  - git clone https://github.com/yafred/asn1-playground.git
  - cd asn1-playground
  - git tag -a $TRAVIS_TAG -m "Refresh docker image"
  - git push -f -q --follow-tags https://${GH_TOKEN}@github.com/yafred/asn1-playground master
  on:
    tags: true
