language: java

jdk:
  - openjdk8

install: true
 
script:
  - mvn package -DskipTests=false -Dmaven.javadoc.skip=true -B -V

after_success:
  - # Prepare files for deploy stage
  - mv tool/target/tool-1.0-SNAPSHOT-jar-with-dependencies.jar asn1-tool-with-google-java-format.jar
  - mv tool/target/tool-1.0-SNAPSHOT-jar-with-dependencies-without-google-java-format.jar asn1-tool.jar
  - mv runtime/target/runtime-1.0-SNAPSHOT.jar asn1-runtime.jar
  - # Generate coverage report
  - mvn clean jacoco:prepare-agent test jacoco:report coveralls:report
  - # Push generated Go code to trigger test
  - git clone https://github.com/yafred/asn1-go-test.git
  - cp -r generator/target/generator-output/go/* asn1-go-test/
  - cd asn1-go-test
  - git add . -A
  - git -c user.name='asn1-tool' -c user.email='travis' commit -m  'Test Go code generator' 
  - git push -f -q https://${GH_TOKEN}@github.com/yafred/asn1-go-test master
 
 
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: 
  - asn1-tool-with-google-java-format.jar
  - asn1-tool.jar
  - asn1-runtime.jar
  skip_cleanup: true
  on:
    tags: true
