# workflow name
name: Generate release-artifacts

# on events
on:
  release:
    types: 
        - "created"

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Copy artifacts to dist
        run: |
          mkdir -p ${{ GITHUB_WORKSPACE }}/dist
          cp ${{ GITHUB_WORKSPACE }}/tool/target/tool-1.0-SNAPSHOT-compiler-with-beautifier.jar ${{ GITHUB_WORKSPACE }}/dist/asn1-compiler-with-google-java-format.jar
          cp ${{ GITHUB_WORKSPACE }}/tool/target/tool-1.0-SNAPSHOT-compiler-without-beautifier.jar ${{ GITHUB_WORKSPACE }}/dist/asn1-compiler.jar
          cp ${{ GITHUB_WORKSPACE }}/tool/target/tool-1.0-SNAPSHOT-converter.jar ${{ GITHUB_WORKSPACE }}/dist/asn1-converter.jar
          cp ${{ GITHUB_WORKSPACE }}/runtime/target/runtime-1.0-SNAPSHOT.jar ${{ GITHUB_WORKSPACE }}/dist/asn1-runtime.jar
          ls -l ${{ GITHUB_WORKSPACE }}/dist
 